# Generated by Django 5.2.9 on 2025-12-22 18:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('trade_name', models.CharField(help_text='Nome comercial da empresa', max_length=255, verbose_name='nome fantasia')),
                ('legal_name', models.CharField(help_text='Razão social da empresa', max_length=255, verbose_name='razão social')),
                ('cnpj', models.CharField(help_text='CNPJ no formato: 00.000.000/0000-00', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato: 00.000.000/0000-00', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ')),
                ('email', models.EmailField(help_text='Email principal da empresa', max_length=254, verbose_name='email')),
                ('phone', models.CharField(help_text='Telefone com DDD. Ex: (11) 3333-4444', max_length=20, verbose_name='telefone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, help_text='UF do estado. Ex: SP, RJ, MG', max_length=2, verbose_name='estado')),
                ('zip_code', models.CharField(blank=True, help_text='CEP no formato: 00000-000', max_length=9, verbose_name='CEP')),
                ('logo', models.ImageField(blank=True, help_text='Logo da empresa para exibição no app', null=True, upload_to='companies/logos/', verbose_name='logo')),
                ('points_per_real', models.DecimalField(decimal_places=2, default=1.0, help_text='Quantos pontos o cliente ganha por real gasto. Ex: 1.50', max_digits=5, verbose_name='pontos por real')),
                ('is_active', models.BooleanField(default=True, help_text='Empresa ativa no programa de fidelidade', verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['trade_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('attendant', 'Atendente')], default='attendant', help_text='Proprietário: controle total. Administrador: gerencia mas não deleta. Atendente: apenas registra pontos.', max_length=20, verbose_name='papel')),
                ('is_active', models.BooleanField(default=True, help_text='Se False, o usuário não pode mais acessar esta empresa', verbose_name='ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'membro da empresa',
                'verbose_name_plural': 'membros da empresa',
                'ordering': ['company', 'role', 'user'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(related_name='companies', through='companies.CompanyMember', to=settings.AUTH_USER_MODEL, verbose_name='membros'),
        ),
        migrations.AddIndex(
            model_name='companymember',
            index=models.Index(fields=['user', 'is_active'], name='companies_c_user_id_c0b50e_idx'),
        ),
        migrations.AddIndex(
            model_name='companymember',
            index=models.Index(fields=['company', 'is_active'], name='companies_c_company_1475c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companymember',
            unique_together={('user', 'company')},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['cnpj'], name='companies_c_cnpj_86fb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active', 'deleted_at'], name='companies_c_is_acti_7ec404_idx'),
        ),
    ]
