# Generated by Django 5.2.9 on 2025-12-22 21:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('logo_light', models.ImageField(blank=True, help_text='Logo para fundos claros. Recomendado: PNG com transparência', null=True, upload_to='companies/themes/logos/', verbose_name='logo (tema claro)')),
                ('logo_dark', models.ImageField(blank=True, help_text='Logo para fundos escuros. Recomendado: PNG com transparência', null=True, upload_to='companies/themes/logos/', verbose_name='logo (tema escuro)')),
                ('favicon', models.ImageField(blank=True, help_text='Ícone do navegador. Recomendado: 32x32px ou 64x64px', null=True, upload_to='companies/themes/favicons/', verbose_name='favicon')),
                ('primary_color', models.CharField(default='#1976D2', help_text='Cor principal da marca. Ex: #1976D2 (azul)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato HEX. Ex: #FF5733 ou #FFF', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='cor principal')),
                ('secondary_color', models.CharField(default='#424242', help_text='Cor secundária. Ex: #424242 (cinza escuro)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato HEX. Ex: #FF5733 ou #FFF', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='cor secundária')),
                ('accent_color', models.CharField(default='#FF5722', help_text='Cor de destaque/ação. Ex: #FF5722 (laranja)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato HEX. Ex: #FF5733 ou #FFF', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='cor de destaque')),
                ('success_color', models.CharField(default='#4CAF50', help_text='Cor para mensagens de sucesso. Ex: #4CAF50 (verde)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato HEX. Ex: #FF5733 ou #FFF', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='cor de sucesso')),
                ('warning_color', models.CharField(default='#FF9800', help_text='Cor para avisos. Ex: #FF9800 (laranja)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato HEX. Ex: #FF5733 ou #FFF', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='cor de aviso')),
                ('error_color', models.CharField(default='#F44336', help_text='Cor para erros. Ex: #F44336 (vermelho)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato HEX. Ex: #FF5733 ou #FFF', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='cor de erro')),
                ('text_primary', models.CharField(default='#212121', help_text='Cor do texto principal. Ex: #212121 (preto)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato HEX. Ex: #FF5733 ou #FFF', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='texto principal')),
                ('text_secondary', models.CharField(default='#757575', help_text='Cor do texto secundário. Ex: #757575 (cinza)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato HEX. Ex: #FF5733 ou #FFF', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='texto secundário')),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Cor do fundo principal. Ex: #FFFFFF (branco)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato HEX. Ex: #FF5733 ou #FFF', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='fundo principal')),
                ('background_secondary', models.CharField(default='#FAFAFA', help_text='Cor do fundo secundário. Ex: #FAFAFA (cinza muito claro)', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato HEX. Ex: #FF5733 ou #FFF', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='fundo secundário')),
                ('card_background', models.CharField(default='#FFFFFF', help_text='Cor de fundo dos cards/cartões. Ex: #FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Cor deve estar no formato HEX. Ex: #FF5733 ou #FFF', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='fundo de cartões')),
                ('custom_css', models.TextField(blank=True, help_text='CSS adicional para customizações avançadas (use com cuidado)', verbose_name='CSS customizado')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Configurações adicionais em formato JSON. Ex: {"border_radius": "8px", "font_family": "Roboto"}', verbose_name='configurações extras')),
                ('is_active', models.BooleanField(default=True, help_text='Se False, usa o tema padrão do sistema', verbose_name='tema ativo')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'tema da empresa',
                'verbose_name_plural': 'temas das empresas',
                'ordering': ['company'],
            },
        ),
    ]
